apiVersion: apps/v1
kind: Deployment
metadata:
  name: collision-parts-inference
  labels:
    app: collision-parts-inference
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collision-parts-inference
  template:
    metadata:
      labels:
        app: collision-parts-inference
        version: v1
    spec:
      containers:
      - name: inference-api
        image: collision-parts:inference-latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: model-storage
          mountPath: /app/data/artifacts
          readOnly: true
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      imagePullSecrets:
      - name: docker-registry-secret