# Data configuration
raw_data:
  stanford_cars_dir: ${paths.data_dir}/raw/stanford_cars
  vehide_annotations: ${paths.data_dir}/raw/vehide_annotations.json
  vehide_images_dir: ${paths.data_dir}/raw/vehide_images

processed_data:
  merged_annotations: ${paths.data_dir}/processed/merged_annotations.json
  train_annotations: ${paths.data_dir}/processed/train_annotations.json
  val_annotations: ${paths.data_dir}/processed/val_annotations.json
  test_annotations: ${paths.data_dir}/processed/test_annotations.json
  yolo_dir: ${paths.data_dir}/processed/yolo
  features_dir: ${paths.data_dir}/processed/features

# Dataset splits
split_ratios:
  train: 0.7
  val: 0.15
  test: 0.15

# Random seeds for reproducible splits
split_seed: 42
augmentation_seed: 123

# Image preprocessing
image_size: 224
mean: [0.485, 0.456, 0.406]  # ImageNet means
std: [0.229, 0.224, 0.225]   # ImageNet stds

# Class configuration
classes:
  - no_damage
  - dent
  - paint_scratch
  - rust
  - crack
  - broken_glass
  - bumper_damage
  - headlight_damage
  - wheel_damage
  - mirror_damage

num_classes: 10

# Sampling configuration for no_damage class
no_damage_samples: 5000  # Number of samples to extract from Stanford Cars